### ISSUE TITLE
add some more info to the readme

### ISSUE THREAD

**Issue by robertmuth** [DiUS/esp-picotts#1]
Thanks for creating this library - I hope to adapt it to work with platformio / arduino

Could you add a few more details to the readme:
1) what is the speed at which an esp32-s3 can synthesize speech from text?
  (is is faster than realtime? is there an initial latency? is the total compute time roughly proportionel to the input text).
2) did you have to make any changes to the svoxpico code?

**Comment by jmattsson** [comment]
Sorry for the horribly late response. I'd managed to not have notifications enabled for this repo 🤦‍♀️

I'll update the readme per request, but to directly answer your questions:

  1. Real-time speech generation is possible, and the initial latency is not really noticeable (in my opinion). I wrote a blog post which also has a small demo video attached: https://dius.com.au/machine-learning-on-the-edge-speech-command-recognition/
  2. No changes were made to the original source of picotts, though I did have to wrap/replace the resource loaders to make it possible to access the models directly from flash rather than having to load them into RAM (see `esp_picorsrc.c`). The source in the `pico/` directory is unmodified.
